# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/6f3aac1f-4f55-4763-5480-0dc6feb86f11/volume/rsync-recipes/conda-4.8.3-python_3.8-on-osx, last modified Fri Mar 13 11:34:34 2020
# ------------------------------------------------

package:
    name: conda
    version: 4.8.3
source:
    fn: conda-4.8.3.tar.gz
    sha256: 123fc5b953fb62d85351f9f87b22b3849791d4d9818d790fe66e740058619259
    url: https://github.com/conda/conda/archive/4.8.3.tar.gz
build:
    always_include_files:
        - bin/activate
        - bin/conda
        - bin/deactivate
    number: '0'
    string: py38_0
requirements:
    host:
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py38_0
        - conda-package-handling 1.6.0 py38h1de35cc_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.2 h0a44026_0
        - openssl 1.1.1d h1de35cc_4
        - pip 20.0.2 py38_1
        - python 3.8.1 h359304d_1
        - readline 7.0 h1de35cc_5
        - ruamel_yaml 0.15.87 py38h1de35cc_0
        - setuptools 46.0.0 py38_0
        - six 1.14.0 py38_0
        - sqlite 3.31.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - tqdm 4.42.1 py_0
        - wheel 0.34.2 py38_0
        - xz 5.2.4 h1de35cc_4
        - yaml 0.1.7 hc338f04_2
        - zlib 1.2.11 h1de35cc_3
    run:
        - conda-package-handling >=1.3.0
        - pycosat >=0.6.3
        - pyopenssl >=16.2.0
        - python >=3.8,<3.9.0a0
        - requests >=2.18.4,<3
        - ruamel_yaml >=0.11.14,<0.16
        - setuptools >=31.0.1
    run_constrained:
        - conda-build >=3
        - conda-env >=2.6
        - cytoolz >=0.8.1
test:
    downstreams:
        - conda-smithy
    files:
        - test_conda.sh
    imports:
        - conda
        - conda_env
    requires:
        - mock
        - pexpect
        - pytest
        - responses
    source_files:
        - conftest.py
        - setup.cfg
        - tests
about:
    description: 'Conda is an open source package management system and environment
        management system for installing multiple versions of software packages and
        their dependencies and switching easily between them. It works on Linux, OS
        X and Windows, and was created for Python programs but can package and distribute
        any software.

        '
    dev_url: https://github.com/conda/conda
    doc_url: https://conda.io/projects/conda/en/latest/
    home: https://conda.io
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: OS-agnostic, system-level binary package and environment manager.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - kalefranz
        - mbargull
        - mcg1969
        - mingwandroid
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
