# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/997c0403-b358-4fab-6876-a73e40fbcfa4/volume/aggregate/pysocks-feedstock/recipe, last modified Fri Nov  8 02:13:08 2019
# ------------------------------------------------

package:
    name: pysocks
    version: 1.7.1
source:
    sha256: 3f8804571ebe159c380ac6de37643bb4685970655d3bba243530d6558b799aa0
    url: https://pypi.io/packages/source/P/PySocks/PySocks-1.7.1.tar.gz
build:
    number: '0'
    script: /opt/concourse/worker/volumes/live/997c0403-b358-4fab-6876-a73e40fbcfa4/volume/pysocks_1573201064549/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install . --no-deps -vv
    string: py38_0
requirements:
    host:
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py38_0
        - libcxx 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - libedit 3.1.20181209 hb402a30_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - openssl 1.1.1d h1de35cc_3
        - pip 19.3.1 py38_0
        - python 3.8.0 h359304d_2
        - readline 7.0 h1de35cc_5
        - setuptools 41.6.0 py38_0
        - sqlite 3.30.1 ha441bb4_0
        - tk 8.6.8 ha441bb4_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
    run:
        - python >=3.8,<3.9.0a0
test:
    imports:
        - socks
about:
    dev_url: https://github.com/Anorov/PySocks
    doc_url: https://github.com/Anorov/PySocks/blob/master/README.md
    home: https://github.com/Anorov/PySocks
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A Python SOCKS client module. See https://github.com/Anorov/PySocks for
        more information.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pmlandwehr
